# Inspired by http://sachachua.com/blog/2015/02/continuous-integration-code-coverage-emacs-packages-travis-coveralls/

language: emacs-lisp
sudo: false

env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-25.3-travis
    - EVM_EMACS=emacs-26.3-travis-linux-xenial
    - EVM_EMACS=emacs-27.1-travis-linux-xenial
    - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

before_install:
  - export PATH="$HOME/.evm/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp
  - evm install ${EVM_EMACS} --use --skip

script:
  - emacs --version
  - make elc
  - make check

notifications:
  email: true
